// Maps food/exercise categories to icon paths in backoffice public assets
// Icons should be placed under: public/assets/icons/categories/*.png
const base = '/assets/icons/categories'

export const categoryIcons = {
  fruits: `${base}/fruits.png`,
  fruit: `${base}/fruits.png`,
  vegetables: `${base}/vegetables.png`,
  vegetable: `${base}/vegetables.png`,
  bread: `${base}/bread.png`,
  general: `${base}/general.png`,
  sugar: `${base}/sugar.png`,
  meat: `${base}/meat.png`,
  canned: `${base}/meat.png`,
  dairy: `${base}/dairy.png`,
  cheese: `${base}/dairy.png`,
  grains: `${base}/grains.png`,
  grain: `${base}/grains.png`,
  nuts: `${base}/nuts.png`,
  nut: `${base}/nuts.png`,
  fish: `${base}/fish.png`,
  fastfood: `${base}/fastfood.png`,
  beverages: `${base}/beverages.png`,
  beverage: `${base}/beverages.png`,
  sweets: `${base}/sweets.png`,
  sweet: `${base}/sweets.png`,
  fats: `${base}/fats.png`,
  fat: `${base}/fats.png`,
  sauces: `${base}/sauces.png`,
  sauce: `${base}/sauces.png`,
  legumes: `${base}/legumes.png`,
  legume: `${base}/legumes.png`,
  snack: `${base}/snack.png`,
  alcohol: `${base}/alcohol.png`,
  desserts: `${base}/sugar.png`,
  dessert: `${base}/sugar.png`,
  condiments: `${base}/condiments.png`,
  condiment: `${base}/condiments.png`,
  eggs: `${base}/eggs.png`,
  egg: `${base}/eggs.png`,
  exerciseGeneral: `${base}/exercise_general.png`,
  suplimente: `${base}/protein.png`,
  supliment: `${base}/protein.png`,
  protein: `${base}/protein.png`,
  seeds: `${base}/nuts.png`,
  seed: `${base}/nuts.png`,
  sosuri: `${base}/sauces.png`,
  grasimi: `${base}/fats.png`,
  mezeluri: `${base}/meat.png`,
  carne: `${base}/meat.png`,
  lactate: `${base}/dairy.png`,
  seminte: `${base}/nuts.png`,
  condimente: `${base}/condiments.png`,
  fructe: `${base}/fruits.png`,
  peste: `${base}/fish.png`,
  oua: `${base}/eggs.png`,
  bauturi: `${base}/beverages.png`,
  'spices & seasonings': `${base}/condiments.png`,
  drinks: `${base}/beverages.png`,
  biscuits: `${base}/sweets.png`,
  soya_products: `${base}/nuts.png`,
  seafood: `${base}/fish.png`,
  dairies: `${base}/dairy.png`,
  meats: `${base}/meat.png`,
  snacks: `${base}/snack.png`,
  breads: `${base}/bread.png`,
  pastas: `${base}/pasta.png`,
  pasta: `${base}/pasta.png`,
  salami: `${base}/meat.png`,
  ham: `${base}/meat.png`,
  hams: `${base}/meat.png`,
  sausages: `${base}/meat.png`
}

export const getCategoryIcon = categoryRaw => {
  const key = String(categoryRaw || '').toLowerCase()
  return categoryIcons[key] || `${base}/general.png`
}
